component implements="coldlight.plugins.pluginInterface" {

	public function init(markdown.flexmark markdownObj, coldsoup.coldsoup coldsoupObj) {
		
		variables.jsoupObj=arguments.coldsoupObj;
		
		return this;
	}

	public string function preProcess(required string text) localmode=true {

		/**
		 * Process the whole text string before processings
		 *
		 * arguments.text = Replace(arguments.text,"♠","&spade;","all");
		 * 
		 */
		return arguments.text;
		
	}

	public void function process(required struct section, required struct document) localmode=true {

		definitionListsToTables( section = arguments.section );
		wrapTables( section = arguments.section );
		markTableEdges( section = arguments.section );
		processImageReplacement( section = arguments.section, document=arguments.document );
	}

	/** Convert definition groups to two columns, retaining markup and node attributes. */
	public void function definitionListsToTables(required struct section) localmode=true {
		lists = arguments.section.node.select("dl");

		// Convert inner lists first so nested definitions remain intact when moved.
		for (listIndex = lists.size() - 1; listIndex >= 0; listIndex--) {
			list = lists.get(listIndex);
			children = list.children();
			supported = true;
			for (child in children) {
				if (!child.is("dt, dd, div")) {
					supported = false;
					break;
				}
				if (child.is("div")) {
					for (entry in child.children()) {
						if (!entry.is("dt, dd")) supported = false;
					}
				}
			}
			// Leave unrecognised structures intact rather than discarding content.
			if (!supported) continue;

			table = list.ownerDocument().createElement("table");
			table.attributes().addAll(list.attributes());
			table.addClass("definition-list");
			entries = [];
			for (child in children) {
				if (child.is("div")) {
					if (entries.len()) {
						appendDefinitionRows(table.appendElement("tbody"), entries);
						entries = [];
					}
					// HTML also permits definition groups wrapped in div elements.
					body = table.appendElement("tbody");
					body.attributes().addAll(child.attributes());
					groupedEntries = [];
					for (entry in child.children()) groupedEntries.append(entry);
					appendDefinitionRows(body, groupedEntries);
				} else {
					entries.append(child);
				}
			}
			if (entries.len()) appendDefinitionRows(table.appendElement("tbody"), entries);
			list.replaceWith(table);
		}
	}

	private void function appendDefinitionRows(required any body, required array entries) localmode=true {
		groups = [];
		group = {terms:[], definitions:[]};
		for (entry in arguments.entries) {
			if (entry.is("dt")) {
				if (group.definitions.len()) {
					groups.append(group);
					group = {terms:[], definitions:[]};
				}
				group.terms.append(entry);
			} else {
				group.definitions.append(entry);
			}
		}
		if (group.terms.len() || group.definitions.len()) groups.append(group);

		for (group in groups) {
			row = arguments.body.appendElement("tr");
			if (group.terms.len() == 1) {
				termCell = group.terms[1].tagName("td");
				row.appendChild(termCell);
			} else {
				termCell = row.appendElement("td");
				// Several terms can share the same group of definitions.
				for (term in group.terms) termCell.appendChild(term.tagName("div"));
			}
			termCell.addClass("definition-term");
			termCell.attr("valign", "top");
			if (group.definitions.len() > 1)
				termCell.attr("rowspan", toString(group.definitions.len()));

			if (!group.definitions.len()) row.appendElement("td");
			for (i = 1; i <= group.definitions.len(); i++) {
				if (i > 1) row = arguments.body.appendElement("tr");
				definitionCell = group.definitions[i].tagName("td");
				definitionCell.addClass("definition-description");
				row.appendChild(definitionCell);
			}
		}
	}

	/** Keep small tables together, including tables generated by this plugin. */
	public void function wrapTables(required struct section) localmode=true {
		for (table in arguments.section.node.select("table:not(.large)")) {
			if (!table.parent().is("div.nobreak")) {
				table.wrap('<div class="nobreak"></div>');
			}
		}
	}

	/** Mark table boundaries using logical columns, including merged cells. */
	public void function markTableEdges(required struct section) localmode=true {
		for (table in arguments.section.node.select("table")) {
			rows = [];
			// Descendant tables are processed separately.
			for (row in table.select("tr")) {
				if (row.closest("table").equals(table)) {
					row.removeClass("first-row").removeClass("last-row");
					rows.append(row);
				}
			}
			if (!rows.len()) continue;
			rows[1].addClass("first-row");
			rows[rows.len()].addClass("last-row");

			occupied = {};
			placements = [];
			width = 0;
			for (rowIndex = 1; rowIndex <= rows.len(); rowIndex++) {
				row = rows[rowIndex];
				// Row spans cannot cross a thead/tbody/tfoot boundary.
				if (rowIndex == 1 || !row.parent().equals(rows[rowIndex - 1].parent())) {
					occupied = {};
					groupEnd = rowIndex;
					while (groupEnd < rows.len() && rows[groupEnd + 1].parent().equals(row.parent()))
						groupEnd++;
				}
				column = 1;
				for (cell in row.children()) {
					if (!cell.is("td, th")) continue;
					cell.removeClass("first-column").removeClass("last-column");
					while (occupied.keyExists(column) && occupied[column] >= rowIndex) column++;

					colspan = tableSpan(cell.attr("colspan"), 1000);
					rowspan = cell.attr("rowspan") == "0"
						? groupEnd - rowIndex + 1
						: tableSpan(cell.attr("rowspan"), 65534);
					endColumn = column + colspan - 1;
					placements.append({node:cell, first:column, last:endColumn});
					width = max(width, endColumn);
					for (covered = column; covered <= endColumn; covered++)
						occupied[covered] = min(groupEnd, rowIndex + rowspan - 1);
					column = endColumn + 1;
				}
			}
			for (placement in placements) {
				if (placement.first == 1) placement.node.addClass("first-column");
				if (placement.last == width) placement.node.addClass("last-column");
			}
		}
	}

	private numeric function tableSpan(required string value, required numeric maximum) {
		if (!reFind("^[0-9]+$", trim(arguments.value))) return 1;
		return max(1, min(arguments.maximum, val(arguments.value)));
	}

	public void function processImageReplacement(required struct section, required struct document) localmode=true {

		images = arguments.section.node.select("[data-image]");
		path = arguments.document.meta.image_base ? : "";
		for ( el in images ) {
				
			image = arguments.section.node.createElement("img");
			image.attr("src", path & el.attr("data-image"));
			image.attr("alt", "");
			if (el.hasAttr("width")) {
				image.attr("width", el.attr("width"));
			}
			for (className in el.classNames()) {
				image.addClass(className);
			}
			el.replaceWith(image);
			
		}
		
	}

}
